### ISSUE TITLE
PPO loading stopped working correctly

### ISSUE THREAD

**Issue by krezelj** [krezelj/wut-curriculum-learning#176]
I'm not sure what happened but for some reason loading stopped working correctly. During the first training after loading the program raises an error about mismatching lengths of tensors (they seem to be off by one but I'm not sure). I'll have to investigate it and try to fix it but it's not a major issue so we can continue with the experiment phase and I'll try to fix it as soon as I can.

**Comment by maciejors** [comment]
`test_saving_loading` doesn't pass no more although it might be related to some different issue. Either way feels like it's important to resolve this asap
